### ISSUE TITLE
Doesn't support 1.31.5 and later?

### ISSUE THREAD

**Issue by callmws** [steeno/EU4ConsolePatcher#14]
Testing this out against the latest patches gives a pattern not found error. Any chance this could be updated or is it not working from my side only?

**Comment by steeno** [comment]
Hi @callmws , will test it tonight / this weekend. Can't remember the latest version i tested it successfully with. Should be at least 1.31.4 if i remember correctly. Is 1.31.5 new? Haven't followed EU4 much after the personal disappointment of the leviathan update.

edit: Are you using the steam, gamepass or the new free epic version?

**Comment by callmws** [comment]
1.31.5 was released a month and a bit I think, and two days ago, they released 1.31.6. Doesn't work on that. 

I'm using Steam. Not sure if it works for the Steam version?

Thanks.

**Comment by steeno** [comment]
Ok this is interesting. I just tried the latest version of the console enabler with version 1.30.6.0 of EU4 and it was still working.
Either way i published a small update, which uses static addresses as fallback, if the right memory location could not be determined via the patterns. Could you try https://github.com/steeno/EU4ConsolePatcher/releases/tag/v1.30.6.0 ?
And yes this was originally done for the steam version, which i also mainly use.

EDIT: I also added a new cheatengine table for eu4 1.30.6.0, which uses static addresses, so is only valid for version 1.30.6.0, named eu4_v1.30.6.0_static_offset_ironman_console_enabler.CT.
I also added the aobscan cheatengine table again which, like my application, tries to find the correct address based on a memory pattern. So you may try one of these too.

Additionally you could try to use the DEBUG version and post the output of it here so that i maybe get a better overview why it fails on your side. You can remove the processlist which gets printed. Should look like:

```Trying to enable debug privileges for the current process
Debug privileges enabled
Trying to find process eu4.exe
...
process name: eu4.exe
th32ProcessID: 0x32b0
th32ModuleID: 0x0
eu4.exe process found
Trying to find module eu4.exe
module name: eu4.exe
modBaseAddress: 0x7ff6ee070000
modBaseSize: 0x2667000
eu4.exe module found
Trying to find memory patterns
processHandle: 0x0000000000000108
BaseAddress: 0x00007FF6EE070000
RegionSize: 0x1000
PageSize: 0x1000
bytesRead: 2667000
pattern: 74 ?? C6 44 24 28 00 41 B8 35 00 00 00
offset: 0x14b2a77
First memory pattern found
processHandle: 0x000000000000010C
BaseAddress: 0x00007FF6EE070000
RegionSize: 0x1000
PageSize: 0x1000
bytesRead: 2667000
pattern: 74 ?? C7 04 25 00 00 00 00 39 05 00 00
offset: 0x14b2c67
Second memory pattern found
Trying to apply patches
Trying to patch: 0x7ff6ef522a77:1
processHandle: 0x000000000000010C
BaseAddress: 0x00007FF6EF522000
RegionSize: 0x510000
PageSize: 0x1000
bytesWritten: 1
Patch applied successfully
Trying to patch: 0x7ff6ef522c67:1
processHandle: 0x0000000000000108
BaseAddress: 0x00007FF6EF522000
RegionSize: 0x510000
PageSize: 0x1000
bytesWritten: 1
Patch applied successfully

**Comment by callmws** [comment]
Weirdest thing happened. The patcher worked on its own after I restarted my PC and it didn't give me an error at all. The game slowed down just a bit, not sure if that's from the patcher but nothing really major.

I'll try the newer version and see if it works as well/better for me. Thanks for the quick fix.

**Comment by steeno** [comment]
^^ I think this is not the first time someone says that it magically worked all of a sudden. But nice to hear that it was not a major issue in your case.
Regarding the performance, you are also not the first who mentioned this. It makes not much sense in my opinion and i have even without the patch performance issues since i don't know? 1.29.x or 1.30.x? where my fps drop from 144 to around 30-40 even if the game is PAUSED after i play for 60 minutes or so. Which is also partly the reason why i currently don't play eu4 much anymore ^^
Dunno if you have cheat engine installed on your system. But you may use the cheattable instead of the application and check if the performance is then also noticeably worse compared to a clean game. The cheattable also has preconfigured hotkeys (ctrl+shift+c) which allows to enable/disable the patch on the fly ingame, so at least after disabling the patch the game should run normally again.
